language: python
python:
  - "3.7"

install:
  - python setup.py install
  - pip install -r requirements-test.txt

script:
  - cd tests
  - pytest --cov=test_macro --cov-report term-missing .

after_success:
  - coveralls
